### ISSUE TITLE
Lists of parameters

### ISSUE THREAD

**Issue by aornugent** [pboesu/debinfer#28]
Dear Dr. Boersch-Supan (and collaborators).

Quick question: is there a simple way to perform inference for lists of parameters?

For example, in a consumer resource model each species has it's own growth rate. In deSolve I can pass this in as a list and evaluate a series of equations using a loop.

My first intuition was to initialise multiple values when declaring the parameter:
```{r}
mu <- debinfer_par(name = "mu", var.type = "de", fixed = FALSE,
          value = rep(0.5, n),
          prior = "norm", hypers = list(mean = 0, sd = 1), 
          prop.var = 0.0001, samp.type="rw")
```

My second is to write everything out long-hand `mu1, mu2, ...` which I'd like to avoid.

Any help appreciated,

Cheers,
Andrew

**Comment by pboesu** [comment]
HI Andrew,

given the way the parameter data structures are handled internally during the MCMC procedure there is no easy way to vectorize the treatment of individual parameters.

However, the initialised `debinfer_parlist` data structure resulting from a `setup_ debinfer()` call is really just a nested list that can be manipulated in a "brute-force" manner using the usual list accessors `[]` and `[[ ]]`. 

My suggestion therefore would be to write a script that performs the entire inference for a single parameter, and build an outer loop around that that iterates over your parameter list and updates the inference procedure for each parameter value by modifying the `debinfer_parlist` object.

I hope that helps,
Philipp
