### ISSUE TITLE
dependency ‘PBSddesolve’ is not available for package ‘deBInfer’

### ISSUE THREAD

**Issue by cmgoold** [pboesu/debinfer#30]
The ```PBSddesolve``` package is not available for download anymore, which is causing this dependency clash. Is there a way around it?
Thanks

**Comment by pboesu** [comment]
Hi Conor,

it's still listed on CRAN: https://cran.r-project.org/web/packages/PBSddesolve/index.html 
Can you install it manually? 

(it does look like `PBSddesolve` now has an R 3.5 requirement, which isn't reflected in the Depends for `deBInfer` - i'll try to fix that, but that wouldn't change the situation if you are working under an olderversion of R)

**Comment by cmgoold** [comment]
Ah, I'm actually running an older version of R (3.4.4) because I use Debian stable. I'll try to update my R version via backports!

**Comment by cmgoold** [comment]
All sorted now, thanks!

**Comment by pboesu** [comment]
Formal R version requirement >= 3.5.0 added in 58342778f24f7a9dffdb38613eb6f7c2c6c02515
