### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by trashbirdecology** [pboesu/debinfer#31]
A suggestion to add a CoC.

**Comment by pboesu** [comment]
Thanks for the suggestion. Happy to add one. Do you have a template for one in mind?

**Comment by trashbirdecology** [comment]
I use this template from CombineORg:
https://github.com/TrashBirdEcology/bbsAssistant/blob/master/CODE_OF_CONDUCT.md

**Comment by pboesu** [comment]
Thanks! 
Added with https://github.com/pboesu/debinfer/pull/32
