### ISSUE TITLE
how to implement inter-dependent initial conditions for systems of constant population size

### ISSUE THREAD

**Issue by benmaier** [pboesu/debinfer#33]
Thank you so for much for this promising-looking package!

I was wondering how one would go about defining initial conditions that depend on each other. In population dynamics with a constant number of individuals, e.g.

```
dA/dt = -A
dB/dt = +A,
```

the total number of individuals is given by `N = A(t) + B(t) = const` at all times . If I want to use `B(0)` as a parameter to infer, is there any way to tell the package that at all times

```
A(0) = N - B(0)
```

while `B(0)` is not fixed?

**Comment by benmaier** [comment]
Just thought of the obvious solution. Since constant population size is a constraint, we can get rid of one equation by setting 

```
A = N - B
dA/dt = -dB/dt
```

i.e. explicitly reduce the system by one equation.

**Comment by pboesu** [comment]
In cases where you can't reduce your system as above, there is a possibility to use parameter-dependent initial values. This is currently not implemented in the main branch of the package, but is described in this paper https://doi.org/10.1101/259705 and the corresponding development branch of deBInfer can be found here: https://github.com/pboesu/debinfer/tree/recalc-inits
