### ISSUE TITLE
Selecting prior in deBInfer

### ISSUE THREAD

**Issue by palakgoel03** [pboesu/debinfer#34]
How to use truncated normal distribution as a prior in deBInfer?

**Comment by pboesu** [comment]
you can specify truncated priors by loading the `truncdist` package and using the distributions implemented in `truncdist::dtrunc`. 
E.g. for a normal prior with mean = 1 and sd = 1 with truncation bounds [1,3], the relevant arguments to `debinfer_par` should look something like this
`prior = "trunc",  hypers = list(spec="norm", mean=1, sd=1, a=1, b=3)`

**Comment by palakgoel03** [comment]
Okay, thank you for your response.
